var routes = new Array();
/*
routes.push([0,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,1,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,3,Infinity,6]);
routes.push([2,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,4,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,4,Infinity,1,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,4,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,4,5,Infinity,Infinity,Infinity,3,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,0,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,6,Infinity,Infinity,4]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,0,Infinity,6,Infinity,Infinity,Infinity,5,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,4,Infinity,Infinity,Infinity,4,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,4]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,1,Infinity,Infinity,6,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,1,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,3,3,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,6,Infinity,Infinity,Infinity,2,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([5,Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,Infinity,3,Infinity,Infinity,Infinity]);
routes.push([1,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity]);
routes.push([4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,3,Infinity,6,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,0,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,2,4,Infinity,Infinity,Infinity,Infinity,2,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,4,Infinity,4,2,Infinity,5,Infinity,1,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,2,Infinity,Infinity,Infinity,0,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,5,2,Infinity,2,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,6,5,Infinity,Infinity,1,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([2,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,3,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,6,Infinity,0,5,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,5,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,2,Infinity,Infinity,6]);
routes.push([Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,1,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,1,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,2,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,0,Infinity,Infinity,Infinity]);
routes.push([Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,1,Infinity,Infinity,0,Infinity,Infinity]);
routes.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,2,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity]);
routes.push([Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,4,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,0]);
*/



routes[0][0] = 0;
routes[0][1] = Infinity;
routes[0][2] = Infinity;
routes[0][3] = 2;
routes[0][4] = Infinity;
routes[0][5] = Infinity;
routes[0][6] = Infinity;
routes[0][7] = Infinity;
routes[0][8] = Infinity;
routes[0][9] = Infinity;
routes[0][10] = Infinity;
routes[0][11] = Infinity;
routes[0][12] = Infinity;
routes[0][13] = Infinity;
routes[0][14] = Infinity;
routes[0][15] = 5;
routes[0][16] = Infinity;
routes[0][17] = 1;
routes[0][18] = 4;
routes[0][19] = Infinity;
routes[0][20] = Infinity;
routes[0][21] = Infinity;
routes[0][22] = Infinity;
routes[0][23] = Infinity;
routes[0][24] = Infinity;
routes[0][25] = 2;
routes[0][26] = Infinity;
routes[0][27] = Infinity;
routes[0][28] = Infinity;
routes[0][29] = Infinity;
routes[0][30] = Infinity;
routes[0][31] = Infinity;
routes[0][32] = Infinity;
routes[0][33] = Infinity;
routes[0][34] = Infinity;
routes[0][35] = Infinity;
routes[1][0] = Infinity;
routes[1][1] = 0;
routes[1][2] = Infinity;
routes[1][3] = Infinity;
routes[1][4] = Infinity;
routes[1][5] = Infinity;
routes[1][6] = Infinity;
routes[1][7] = Infinity;
routes[1][8] = Infinity;
routes[1][9] = Infinity;
routes[1][10] = Infinity;
routes[1][11] = Infinity;
routes[1][12] = Infinity;
routes[1][13] = Infinity;
routes[1][14] = Infinity;
routes[1][15] = Infinity;
routes[1][16] = 2;
routes[1][17] = Infinity;
routes[1][18] = Infinity;
routes[1][19] = 2;
routes[1][20] = Infinity;
routes[1][21] = Infinity;
routes[1][22] = Infinity;
routes[1][23] = Infinity;
routes[1][24] = Infinity;
routes[1][25] = Infinity;
routes[1][26] = Infinity;
routes[1][27] = Infinity;
routes[1][28] = Infinity;
routes[1][29] = Infinity;
routes[1][30] = Infinity;
routes[1][31] = Infinity;
routes[1][32] = Infinity;
routes[1][33] = Infinity;
routes[1][34] = Infinity;
routes[1][35] = Infinity;
routes[2][0] = Infinity;
routes[2][1] = Infinity;
routes[2][2] = 0;
routes[2][3] = Infinity;
routes[2][4] = Infinity;
routes[2][5] = Infinity;
routes[2][6] = Infinity;
routes[2][7] = Infinity;
routes[2][8] = Infinity;
routes[2][9] = 4;
routes[2][10] = Infinity;
routes[2][11] = Infinity;
routes[2][12] = Infinity;
routes[2][13] = Infinity;
routes[2][14] = Infinity;
routes[2][15] = Infinity;
routes[2][16] = Infinity;
routes[2][17] = Infinity;
routes[2][18] = Infinity;
routes[2][19] = Infinity;
routes[2][20] = Infinity;
routes[2][21] = Infinity;
routes[2][22] = Infinity;
routes[2][23] = Infinity;
routes[2][24] = Infinity;
routes[2][25] = Infinity;
routes[2][26] = Infinity;
routes[2][27] = Infinity;
routes[2][28] = Infinity;
routes[2][29] = Infinity;
routes[2][30] = 4;
routes[2][31] = Infinity;
routes[2][32] = Infinity;
routes[2][33] = 3;
routes[2][34] = Infinity;
routes[2][35] = 6;
routes[3][0] = 2;
routes[3][1] = Infinity;
routes[3][2] = Infinity;
routes[3][3] = 0;
routes[3][4] = Infinity;
routes[3][5] = Infinity;
routes[3][6] = Infinity;
routes[3][7] = Infinity;
routes[3][8] = Infinity;
routes[3][9] = Infinity;
routes[3][10] = Infinity;
routes[3][11] = Infinity;
routes[3][12] = Infinity;
routes[3][13] = Infinity;
routes[3][14] = Infinity;
routes[3][15] = 4;
routes[3][16] = Infinity;
routes[3][17] = Infinity;
routes[3][18] = Infinity;
routes[3][19] = Infinity;
routes[3][20] = Infinity;
routes[3][21] = Infinity;
routes[3][22] = Infinity;
routes[3][23] = Infinity;
routes[3][24] = Infinity;
routes[3][25] = 2;
routes[3][26] = Infinity;
routes[3][27] = Infinity;
routes[3][28] = Infinity;
routes[3][29] = Infinity;
routes[3][30] = Infinity;
routes[3][31] = Infinity;
routes[3][32] = Infinity;
routes[3][33] = Infinity;
routes[3][34] = Infinity;
routes[3][35] = Infinity;
routes[4][0] = Infinity;
routes[4][1] = Infinity;
routes[4][2] = Infinity;
routes[4][3] = Infinity;
routes[4][4] = 0;
routes[4][5] = Infinity;
routes[4][6] = Infinity;
routes[4][7] = 3;
routes[4][8] = Infinity;
routes[4][9] = Infinity;
routes[4][10] = Infinity;
routes[4][11] = Infinity;
routes[4][12] = Infinity;
routes[4][13] = Infinity;
routes[4][14] = Infinity;
routes[4][15] = Infinity;
routes[4][16] = Infinity;
routes[4][17] = Infinity;
routes[4][18] = Infinity;
routes[4][19] = Infinity;
routes[4][20] = Infinity;
routes[4][21] = 4;
routes[4][22] = Infinity;
routes[4][23] = 3;
routes[4][24] = Infinity;
routes[4][25] = Infinity;
routes[4][26] = Infinity;
routes[4][27] = Infinity;
routes[4][28] = Infinity;
routes[4][29] = Infinity;
routes[4][30] = Infinity;
routes[4][31] = 2;
routes[4][32] = 4;
routes[4][33] = Infinity;
routes[4][34] = Infinity;
routes[4][35] = Infinity;
routes[5][0] = Infinity;
routes[5][1] = Infinity;
routes[5][2] = Infinity;
routes[5][3] = Infinity;
routes[5][4] = Infinity;
routes[5][5] = 0;
routes[5][6] = Infinity;
routes[5][7] = Infinity;
routes[5][8] = 4;
routes[5][9] = Infinity;
routes[5][10] = 1;
routes[5][11] = Infinity;
routes[5][12] = Infinity;
routes[5][13] = 2;
routes[5][14] = Infinity;
routes[5][15] = Infinity;
routes[5][16] = Infinity;
routes[5][17] = Infinity;
routes[5][18] = Infinity;
routes[5][19] = Infinity;
routes[5][20] = 2;
routes[5][21] = Infinity;
routes[5][22] = Infinity;
routes[5][23] = Infinity;
routes[5][24] = Infinity;
routes[5][25] = Infinity;
routes[5][26] = Infinity;
routes[5][27] = Infinity;
routes[5][28] = Infinity;
routes[5][29] = Infinity;
routes[5][30] = Infinity;
routes[5][31] = Infinity;
routes[5][32] = Infinity;
routes[5][33] = Infinity;
routes[5][34] = Infinity;
routes[5][35] = Infinity;
routes[6][0] = Infinity;
routes[6][1] = Infinity;
routes[6][2] = Infinity;
routes[6][3] = Infinity;
routes[6][4] = Infinity;
routes[6][5] = Infinity;
routes[6][6] = 0;
routes[6][7] = Infinity;
routes[6][8] = Infinity;
routes[6][9] = 4;
routes[6][10] = Infinity;
routes[6][11] = 4;
routes[6][12] = Infinity;
routes[6][13] = Infinity;
routes[6][14] = Infinity;
routes[6][15] = Infinity;
routes[6][16] = Infinity;
routes[6][17] = Infinity;
routes[6][18] = Infinity;
routes[6][19] = Infinity;
routes[6][20] = 4;
routes[6][21] = 4;
routes[6][22] = 5;
routes[6][23] = Infinity;
routes[6][24] = Infinity;
routes[6][25] = Infinity;
routes[6][26] = 3;
routes[6][27] = Infinity;
routes[6][28] = 2;
routes[6][29] = Infinity;
routes[6][30] = Infinity;
routes[6][31] = Infinity;
routes[6][32] = Infinity;
routes[6][33] = Infinity;
routes[6][34] = Infinity;
routes[6][35] = Infinity;
routes[7][0] = Infinity;
routes[7][1] = Infinity;
routes[7][2] = Infinity;
routes[7][3] = Infinity;
routes[7][4] = 3;
routes[7][5] = Infinity;
routes[7][6] = Infinity;
routes[7][7] = 0;
routes[7][8] = Infinity;
routes[7][9] = 6;
routes[7][10] = Infinity;
routes[7][11] = Infinity;
routes[7][12] = Infinity;
routes[7][13] = Infinity;
routes[7][14] = Infinity;
routes[7][15] = Infinity;
routes[7][16] = Infinity;
routes[7][17] = Infinity;
routes[7][18] = Infinity;
routes[7][19] = Infinity;
routes[7][20] = Infinity;
routes[7][21] = 2;
routes[7][22] = Infinity;
routes[7][23] = Infinity;
routes[7][24] = Infinity;
routes[7][25] = Infinity;
routes[7][26] = Infinity;
routes[7][27] = Infinity;
routes[7][28] = Infinity;
routes[7][29] = 3;
routes[7][30] = Infinity;
routes[7][31] = Infinity;
routes[7][32] = 6;
routes[7][33] = Infinity;
routes[7][34] = Infinity;
routes[7][35] = 4;
routes[8][0] = Infinity;
routes[8][1] = Infinity;
routes[8][2] = Infinity;
routes[8][3] = Infinity;
routes[8][4] = Infinity;
routes[8][5] = 4;
routes[8][6] = Infinity;
routes[8][7] = Infinity;
routes[8][8] = 0;
routes[8][9] = Infinity;
routes[8][10] = 6;
routes[8][11] = Infinity;
routes[8][12] = Infinity;
routes[8][13] = Infinity;
routes[8][14] = 5;
routes[8][15] = Infinity;
routes[8][16] = Infinity;
routes[8][17] = Infinity;
routes[8][18] = Infinity;
routes[8][19] = Infinity;
routes[8][20] = 5;
routes[8][21] = Infinity;
routes[8][22] = 3;
routes[8][23] = Infinity;
routes[8][24] = Infinity;
routes[8][25] = Infinity;
routes[8][26] = Infinity;
routes[8][27] = Infinity;
routes[8][28] = 2;
routes[8][29] = Infinity;
routes[8][30] = Infinity;
routes[8][31] = Infinity;
routes[8][32] = Infinity;
routes[8][33] = Infinity;
routes[8][34] = Infinity;
routes[8][35] = Infinity;
routes[9][0] = Infinity;
routes[9][1] = Infinity;
routes[9][2] = 4;
routes[9][3] = Infinity;
routes[9][4] = Infinity;
routes[9][5] = Infinity;
routes[9][6] = 4;
routes[9][7] = Infinity;
routes[9][8] = Infinity;
routes[9][9] = 0;
routes[9][10] = Infinity;
routes[9][11] = Infinity;
routes[9][12] = Infinity;
routes[9][13] = Infinity;
routes[9][14] = Infinity;
routes[9][15] = Infinity;
routes[9][16] = Infinity;
routes[9][17] = Infinity;
routes[9][18] = Infinity;
routes[9][19] = Infinity;
routes[9][20] = Infinity;
routes[9][21] = 5;
routes[9][22] = Infinity;
routes[9][23] = Infinity;
routes[9][24] = Infinity;
routes[9][25] = Infinity;
routes[9][26] = 3;
routes[9][27] = Infinity;
routes[9][28] = Infinity;
routes[9][29] = Infinity;
routes[9][30] = 6;
routes[9][31] = Infinity;
routes[9][32] = Infinity;
routes[9][33] = Infinity;
routes[9][34] = Infinity;
routes[9][35] = 4;
routes[10][0] = Infinity;
routes[10][1] = Infinity;
routes[10][2] = Infinity;
routes[10][3] = Infinity;
routes[10][4] = Infinity;
routes[10][5] = 1;
routes[10][6] = Infinity;
routes[10][7] = Infinity;
routes[10][8] = 6;
routes[10][9] = Infinity;
routes[10][10] = 0;
routes[10][11] = Infinity;
routes[10][12] = Infinity;
routes[10][13] = Infinity;
routes[10][14] = Infinity;
routes[10][15] = Infinity;
routes[10][16] = Infinity;
routes[10][17] = Infinity;
routes[10][18] = 3;
routes[10][19] = Infinity;
routes[10][20] = Infinity;
routes[10][21] = Infinity;
routes[10][22] = Infinity;
routes[10][23] = Infinity;
routes[10][24] = Infinity;
routes[10][25] = Infinity;
routes[10][26] = Infinity;
routes[10][27] = Infinity;
routes[10][28] = Infinity;
routes[10][29] = Infinity;
routes[10][30] = Infinity;
routes[10][31] = Infinity;
routes[10][32] = Infinity;
routes[10][33] = Infinity;
routes[10][34] = Infinity;
routes[10][35] = Infinity;
routes[11][0] = Infinity;
routes[11][1] = Infinity;
routes[11][2] = Infinity;
routes[11][3] = Infinity;
routes[11][4] = Infinity;
routes[11][5] = Infinity;
routes[11][6] = 4;
routes[11][7] = Infinity;
routes[11][8] = Infinity;
routes[11][9] = Infinity;
routes[11][10] = Infinity;
routes[11][11] = 0;
routes[11][12] = Infinity;
routes[11][13] = Infinity;
routes[11][14] = Infinity;
routes[11][15] = Infinity;
routes[11][16] = Infinity;
routes[11][17] = Infinity;
routes[11][18] = Infinity;
routes[11][19] = Infinity;
routes[11][20] = 2;
routes[11][21] = 1;
routes[11][22] = Infinity;
routes[11][23] = Infinity;
routes[11][24] = Infinity;
routes[11][25] = Infinity;
routes[11][26] = Infinity;
routes[11][27] = Infinity;
routes[11][28] = Infinity;
routes[11][29] = Infinity;
routes[11][30] = Infinity;
routes[11][31] = 2;
routes[11][32] = Infinity;
routes[11][33] = Infinity;
routes[11][34] = Infinity;
routes[11][35] = Infinity;
routes[12][0] = Infinity;
routes[12][1] = Infinity;
routes[12][2] = Infinity;
routes[12][3] = Infinity;
routes[12][4] = Infinity;
routes[12][5] = Infinity;
routes[12][6] = Infinity;
routes[12][7] = Infinity;
routes[12][8] = Infinity;
routes[12][9] = Infinity;
routes[12][10] = Infinity;
routes[12][11] = Infinity;
routes[12][12] = 0;
routes[12][13] = Infinity;
routes[12][14] = 2;
routes[12][15] = Infinity;
routes[12][16] = Infinity;
routes[12][17] = Infinity;
routes[12][18] = Infinity;
routes[12][19] = Infinity;
routes[12][20] = Infinity;
routes[12][21] = Infinity;
routes[12][22] = Infinity;
routes[12][23] = Infinity;
routes[12][24] = Infinity;
routes[12][25] = Infinity;
routes[12][26] = 3;
routes[12][27] = Infinity;
routes[12][28] = Infinity;
routes[12][29] = Infinity;
routes[12][30] = Infinity;
routes[12][31] = Infinity;
routes[12][32] = Infinity;
routes[12][33] = Infinity;
routes[12][34] = Infinity;
routes[12][35] = Infinity;
routes[13][0] = Infinity;
routes[13][1] = Infinity;
routes[13][2] = Infinity;
routes[13][3] = Infinity;
routes[13][4] = Infinity;
routes[13][5] = 2;
routes[13][6] = Infinity;
routes[13][7] = Infinity;
routes[13][8] = Infinity;
routes[13][9] = Infinity;
routes[13][10] = Infinity;
routes[13][11] = Infinity;
routes[13][12] = Infinity;
routes[13][13] = 0;
routes[13][14] = Infinity;
routes[13][15] = Infinity;
routes[13][16] = Infinity;
routes[13][17] = 3;
routes[13][18] = 3;
routes[13][19] = Infinity;
routes[13][20] = 2;
routes[13][21] = Infinity;
routes[13][22] = Infinity;
routes[13][23] = Infinity;
routes[13][24] = Infinity;
routes[13][25] = Infinity;
routes[13][26] = Infinity;
routes[13][27] = Infinity;
routes[13][28] = Infinity;
routes[13][29] = Infinity;
routes[13][30] = Infinity;
routes[13][31] = 2;
routes[13][32] = Infinity;
routes[13][33] = Infinity;
routes[13][34] = Infinity;
routes[13][35] = Infinity;
routes[14][0] = Infinity;
routes[14][1] = Infinity;
routes[14][2] = Infinity;
routes[14][3] = Infinity;
routes[14][4] = Infinity;
routes[14][5] = Infinity;
routes[14][6] = Infinity;
routes[14][7] = Infinity;
routes[14][8] = 6;
routes[14][9] = Infinity;
routes[14][10] = Infinity;
routes[14][11] = Infinity;
routes[14][12] = 2;
routes[14][13] = Infinity;
routes[14][14] = 0;
routes[14][15] = Infinity;
routes[14][16] = Infinity;
routes[14][17] = Infinity;
routes[14][18] = Infinity;
routes[14][19] = Infinity;
routes[14][20] = Infinity;
routes[14][21] = Infinity;
routes[14][22] = 3;
routes[14][23] = Infinity;
routes[14][24] = Infinity;
routes[14][25] = Infinity;
routes[14][26] = Infinity;
routes[14][27] = 3;
routes[14][28] = Infinity;
routes[14][29] = Infinity;
routes[14][30] = Infinity;
routes[14][31] = Infinity;
routes[14][32] = Infinity;
routes[14][33] = Infinity;
routes[14][34] = Infinity;
routes[14][35] = Infinity;
routes[15][0] = 5;
routes[15][1] = Infinity;
routes[15][2] = Infinity;
routes[15][3] = 4;
routes[15][4] = Infinity;
routes[15][5] = Infinity;
routes[15][6] = Infinity;
routes[15][7] = Infinity;
routes[15][8] = Infinity;
routes[15][9] = Infinity;
routes[15][10] = Infinity;
routes[15][11] = Infinity;
routes[15][12] = Infinity;
routes[15][13] = Infinity;
routes[15][14] = Infinity;
routes[15][15] = 0;
routes[15][16] = Infinity;
routes[15][17] = Infinity;
routes[15][18] = 6;
routes[15][19] = Infinity;
routes[15][20] = Infinity;
routes[15][21] = Infinity;
routes[15][22] = Infinity;
routes[15][23] = Infinity;
routes[15][24] = Infinity;
routes[15][25] = Infinity;
routes[15][26] = Infinity;
routes[15][27] = Infinity;
routes[15][28] = Infinity;
routes[15][29] = Infinity;
routes[15][30] = Infinity;
routes[15][31] = Infinity;
routes[15][32] = Infinity;
routes[15][33] = Infinity;
routes[15][34] = Infinity;
routes[15][35] = Infinity;
routes[16][0] = Infinity;
routes[16][1] = 2;
routes[16][2] = Infinity;
routes[16][3] = Infinity;
routes[16][4] = Infinity;
routes[16][5] = Infinity;
routes[16][6] = Infinity;
routes[16][7] = Infinity;
routes[16][8] = Infinity;
routes[16][9] = Infinity;
routes[16][10] = Infinity;
routes[16][11] = Infinity;
routes[16][12] = Infinity;
routes[16][13] = Infinity;
routes[16][14] = Infinity;
routes[16][15] = Infinity;
routes[16][16] = 0;
routes[16][17] = Infinity;
routes[16][18] = Infinity;
routes[16][19] = 3;
routes[16][20] = Infinity;
routes[16][21] = Infinity;
routes[16][22] = Infinity;
routes[16][23] = Infinity;
routes[16][24] = Infinity;
routes[16][25] = Infinity;
routes[16][26] = Infinity;
routes[16][27] = Infinity;
routes[16][28] = Infinity;
routes[16][29] = 5;
routes[16][30] = Infinity;
routes[16][31] = Infinity;
routes[16][32] = 3;
routes[16][33] = Infinity;
routes[16][34] = Infinity;
routes[16][35] = Infinity;
routes[17][0] = 1;
routes[17][1] = Infinity;
routes[17][2] = Infinity;
routes[17][3] = Infinity;
routes[17][4] = Infinity;
routes[17][5] = Infinity;
routes[17][6] = Infinity;
routes[17][7] = Infinity;
routes[17][8] = Infinity;
routes[17][9] = Infinity;
routes[17][10] = Infinity;
routes[17][11] = Infinity;
routes[17][12] = Infinity;
routes[17][13] = 3;
routes[17][14] = Infinity;
routes[17][15] = Infinity;
routes[17][16] = Infinity;
routes[17][17] = 0;
routes[17][18] = Infinity;
routes[17][19] = Infinity;
routes[17][20] = Infinity;
routes[17][21] = Infinity;
routes[17][22] = Infinity;
routes[17][23] = 4;
routes[17][24] = Infinity;
routes[17][25] = 3;
routes[17][26] = Infinity;
routes[17][27] = Infinity;
routes[17][28] = Infinity;
routes[17][29] = Infinity;
routes[17][30] = Infinity;
routes[17][31] = 2;
routes[17][32] = Infinity;
routes[17][33] = Infinity;
routes[17][34] = Infinity;
routes[17][35] = Infinity;
routes[18][0] = 4;
routes[18][1] = Infinity;
routes[18][2] = Infinity;
routes[18][3] = Infinity;
routes[18][4] = Infinity;
routes[18][5] = Infinity;
routes[18][6] = Infinity;
routes[18][7] = Infinity;
routes[18][8] = Infinity;
routes[18][9] = Infinity;
routes[18][10] = 2;
routes[18][11] = Infinity;
routes[18][12] = Infinity;
routes[18][13] = 3;
routes[18][14] = Infinity;
routes[18][15] = 6;
routes[18][16] = Infinity;
routes[18][17] = Infinity;
routes[18][18] = 0;
routes[18][19] = Infinity;
routes[18][20] = Infinity;
routes[18][21] = Infinity;
routes[18][22] = Infinity;
routes[18][23] = Infinity;
routes[18][24] = Infinity;
routes[18][25] = Infinity;
routes[18][26] = Infinity;
routes[18][27] = Infinity;
routes[18][28] = Infinity;
routes[18][29] = Infinity;
routes[18][30] = Infinity;
routes[18][31] = Infinity;
routes[18][32] = Infinity;
routes[18][33] = Infinity;
routes[18][34] = Infinity;
routes[18][35] = Infinity;
routes[19][0] = Infinity;
routes[19][1] = 2;
routes[19][2] = Infinity;
routes[19][3] = Infinity;
routes[19][4] = Infinity;
routes[19][5] = Infinity;
routes[19][6] = Infinity;
routes[19][7] = Infinity;
routes[19][8] = Infinity;
routes[19][9] = Infinity;
routes[19][10] = Infinity;
routes[19][11] = Infinity;
routes[19][12] = Infinity;
routes[19][13] = Infinity;
routes[19][14] = Infinity;
routes[19][15] = Infinity;
routes[19][16] = 3;
routes[19][17] = Infinity;
routes[19][18] = Infinity;
routes[19][19] = 0;
routes[19][20] = Infinity;
routes[19][21] = Infinity;
routes[19][22] = Infinity;
routes[19][23] = 2;
routes[19][24] = Infinity;
routes[19][25] = Infinity;
routes[19][26] = Infinity;
routes[19][27] = Infinity;
routes[19][28] = Infinity;
routes[19][29] = Infinity;
routes[19][30] = Infinity;
routes[19][31] = Infinity;
routes[19][32] = Infinity;
routes[19][33] = Infinity;
routes[19][34] = 2;
routes[19][35] = Infinity;
routes[20][0] = Infinity;
routes[20][1] = Infinity;
routes[20][2] = Infinity;
routes[20][3] = Infinity;
routes[20][4] = Infinity;
routes[20][5] = 2;
routes[20][6] = 4;
routes[20][7] = Infinity;
routes[20][8] = Infinity;
routes[20][9] = Infinity;
routes[20][10] = Infinity;
routes[20][11] = 2;
routes[20][12] = Infinity;
routes[20][13] = 2;
routes[20][14] = Infinity;
routes[20][15] = Infinity;
routes[20][16] = Infinity;
routes[20][17] = Infinity;
routes[20][18] = Infinity;
routes[20][19] = Infinity;
routes[20][20] = 0;
routes[20][21] = Infinity;
routes[20][22] = Infinity;
routes[20][23] = Infinity;
routes[20][24] = Infinity;
routes[20][25] = Infinity;
routes[20][26] = Infinity;
routes[20][27] = Infinity;
routes[20][28] = 3;
routes[20][29] = Infinity;
routes[20][30] = Infinity;
routes[20][31] = Infinity;
routes[20][32] = Infinity;
routes[20][33] = Infinity;
routes[20][34] = Infinity;
routes[20][35] = Infinity;
routes[21][0] = Infinity;
routes[21][1] = Infinity;
routes[21][2] = Infinity;
routes[21][3] = Infinity;
routes[21][4] = 4;
routes[21][5] = Infinity;
routes[21][6] = 4;
routes[21][7] = 2;
routes[21][8] = Infinity;
routes[21][9] = 5;
routes[21][10] = Infinity;
routes[21][11] = 1;
routes[21][12] = Infinity;
routes[21][13] = Infinity;
routes[21][14] = Infinity;
routes[21][15] = Infinity;
routes[21][16] = Infinity;
routes[21][17] = Infinity;
routes[21][18] = Infinity;
routes[21][19] = Infinity;
routes[21][20] = Infinity;
routes[21][21] = 0;
routes[21][22] = Infinity;
routes[21][23] = Infinity;
routes[21][24] = Infinity;
routes[21][25] = Infinity;
routes[21][26] = Infinity;
routes[21][27] = Infinity;
routes[21][28] = Infinity;
routes[21][29] = Infinity;
routes[21][30] = Infinity;
routes[21][31] = Infinity;
routes[21][32] = Infinity;
routes[21][33] = Infinity;
routes[21][34] = Infinity;
routes[21][35] = Infinity;
routes[22][0] = Infinity;
routes[22][1] = Infinity;
routes[22][2] = Infinity;
routes[22][3] = Infinity;
routes[22][4] = Infinity;
routes[22][5] = Infinity;
routes[22][6] = 5;
routes[22][7] = Infinity;
routes[22][8] = 3;
routes[22][9] = Infinity;
routes[22][10] = Infinity;
routes[22][11] = Infinity;
routes[22][12] = Infinity;
routes[22][13] = Infinity;
routes[22][14] = 3;
routes[22][15] = Infinity;
routes[22][16] = Infinity;
routes[22][17] = Infinity;
routes[22][18] = Infinity;
routes[22][19] = Infinity;
routes[22][20] = Infinity;
routes[22][21] = Infinity;
routes[22][22] = 0;
routes[22][23] = Infinity;
routes[22][24] = Infinity;
routes[22][25] = Infinity;
routes[22][26] = Infinity;
routes[22][27] = Infinity;
routes[22][28] = 3;
routes[22][29] = Infinity;
routes[22][30] = Infinity;
routes[22][31] = Infinity;
routes[22][32] = Infinity;
routes[22][33] = Infinity;
routes[22][34] = Infinity;
routes[22][35] = Infinity;
routes[23][0] = Infinity;
routes[23][1] = Infinity;
routes[23][2] = Infinity;
routes[23][3] = Infinity;
routes[23][4] = 3;
routes[23][5] = Infinity;
routes[23][6] = Infinity;
routes[23][7] = Infinity;
routes[23][8] = Infinity;
routes[23][9] = Infinity;
routes[23][10] = Infinity;
routes[23][11] = Infinity;
routes[23][12] = Infinity;
routes[23][13] = Infinity;
routes[23][14] = Infinity;
routes[23][15] = Infinity;
routes[23][16] = Infinity;
routes[23][17] = 4;
routes[23][18] = Infinity;
routes[23][19] = 2;
routes[23][20] = Infinity;
routes[23][21] = Infinity;
routes[23][22] = Infinity;
routes[23][23] = 0;
routes[23][24] = Infinity;
routes[23][25] = 2;
routes[23][26] = Infinity;
routes[23][27] = Infinity;
routes[23][28] = Infinity;
routes[23][29] = Infinity;
routes[23][30] = Infinity;
routes[23][31] = 5;
routes[23][32] = 2;
routes[23][33] = Infinity;
routes[23][34] = 2;
routes[23][35] = Infinity;
routes[24][0] = Infinity;
routes[24][1] = Infinity;
routes[24][2] = Infinity;
routes[24][3] = Infinity;
routes[24][4] = Infinity;
routes[24][5] = Infinity;
routes[24][6] = Infinity;
routes[24][7] = Infinity;
routes[24][8] = Infinity;
routes[24][9] = Infinity;
routes[24][10] = Infinity;
routes[24][11] = Infinity;
routes[24][12] = Infinity;
routes[24][13] = Infinity;
routes[24][14] = Infinity;
routes[24][15] = Infinity;
routes[24][16] = Infinity;
routes[24][17] = Infinity;
routes[24][18] = Infinity;
routes[24][19] = Infinity;
routes[24][20] = Infinity;
routes[24][21] = Infinity;
routes[24][22] = Infinity;
routes[24][23] = Infinity;
routes[24][24] = 0;
routes[24][25] = Infinity;
routes[24][26] = 6;
routes[24][27] = 5;
routes[24][28] = Infinity;
routes[24][29] = Infinity;
routes[24][30] = 1;
routes[24][31] = Infinity;
routes[24][32] = Infinity;
routes[24][33] = Infinity;
routes[24][34] = Infinity;
routes[24][35] = Infinity;
routes[25][0] = 2;
routes[25][1] = Infinity;
routes[25][2] = Infinity;
routes[25][3] = 2;
routes[25][4] = Infinity;
routes[25][5] = Infinity;
routes[25][6] = Infinity;
routes[25][7] = Infinity;
routes[25][8] = Infinity;
routes[25][9] = Infinity;
routes[25][10] = Infinity;
routes[25][11] = Infinity;
routes[25][12] = Infinity;
routes[25][13] = Infinity;
routes[25][14] = Infinity;
routes[25][15] = Infinity;
routes[25][16] = Infinity;
routes[25][17] = 3;
routes[25][18] = Infinity;
routes[25][19] = Infinity;
routes[25][20] = Infinity;
routes[25][21] = Infinity;
routes[25][22] = Infinity;
routes[25][23] = 2;
routes[25][24] = Infinity;
routes[25][25] = 0;
routes[25][26] = Infinity;
routes[25][27] = Infinity;
routes[25][28] = Infinity;
routes[25][29] = Infinity;
routes[25][30] = Infinity;
routes[25][31] = Infinity;
routes[25][32] = Infinity;
routes[25][33] = Infinity;
routes[25][34] = 2;
routes[25][35] = Infinity;
routes[26][0] = Infinity;
routes[26][1] = Infinity;
routes[26][2] = Infinity;
routes[26][3] = Infinity;
routes[26][4] = Infinity;
routes[26][5] = Infinity;
routes[26][6] = 3;
routes[26][7] = Infinity;
routes[26][8] = Infinity;
routes[26][9] = 3;
routes[26][10] = Infinity;
routes[26][11] = Infinity;
routes[26][12] = 3;
routes[26][13] = Infinity;
routes[26][14] = Infinity;
routes[26][15] = Infinity;
routes[26][16] = Infinity;
routes[26][17] = Infinity;
routes[26][18] = Infinity;
routes[26][19] = Infinity;
routes[26][20] = Infinity;
routes[26][21] = Infinity;
routes[26][22] = Infinity;
routes[26][23] = Infinity;
routes[26][24] = 6;
routes[26][25] = Infinity;
routes[26][26] = 0;
routes[26][27] = 5;
routes[26][28] = Infinity;
routes[26][29] = Infinity;
routes[26][30] = Infinity;
routes[26][31] = Infinity;
routes[26][32] = Infinity;
routes[26][33] = Infinity;
routes[26][34] = Infinity;
routes[26][35] = Infinity;
routes[27][0] = Infinity;
routes[27][1] = Infinity;
routes[27][2] = Infinity;
routes[27][3] = Infinity;
routes[27][4] = Infinity;
routes[27][5] = Infinity;
routes[27][6] = Infinity;
routes[27][7] = Infinity;
routes[27][8] = Infinity;
routes[27][9] = Infinity;
routes[27][10] = Infinity;
routes[27][11] = Infinity;
routes[27][12] = Infinity;
routes[27][13] = Infinity;
routes[27][14] = 3;
routes[27][15] = Infinity;
routes[27][16] = Infinity;
routes[27][17] = Infinity;
routes[27][18] = Infinity;
routes[27][19] = Infinity;
routes[27][20] = Infinity;
routes[27][21] = Infinity;
routes[27][22] = Infinity;
routes[27][23] = Infinity;
routes[27][24] = 5;
routes[27][25] = Infinity;
routes[27][26] = 5;
routes[27][27] = 0;
routes[27][28] = Infinity;
routes[27][29] = Infinity;
routes[27][30] = Infinity;
routes[27][31] = Infinity;
routes[27][32] = Infinity;
routes[27][33] = Infinity;
routes[27][34] = Infinity;
routes[27][35] = Infinity;
routes[28][0] = Infinity;
routes[28][1] = Infinity;
routes[28][2] = Infinity;
routes[28][3] = Infinity;
routes[28][4] = Infinity;
routes[28][5] = Infinity;
routes[28][6] = 2;
routes[28][7] = Infinity;
routes[28][8] = 2;
routes[28][9] = Infinity;
routes[28][10] = Infinity;
routes[28][11] = Infinity;
routes[28][12] = Infinity;
routes[28][13] = Infinity;
routes[28][14] = Infinity;
routes[28][15] = Infinity;
routes[28][16] = Infinity;
routes[28][17] = Infinity;
routes[28][18] = Infinity;
routes[28][19] = Infinity;
routes[28][20] = 3;
routes[28][21] = Infinity;
routes[28][22] = 3;
routes[28][23] = Infinity;
routes[28][24] = Infinity;
routes[28][25] = Infinity;
routes[28][26] = Infinity;
routes[28][27] = Infinity;
routes[28][28] = 0;
routes[28][29] = Infinity;
routes[28][30] = Infinity;
routes[28][31] = Infinity;
routes[28][32] = Infinity;
routes[28][33] = Infinity;
routes[28][34] = Infinity;
routes[28][35] = Infinity;
routes[29][0] = Infinity;
routes[29][1] = Infinity;
routes[29][2] = Infinity;
routes[29][3] = Infinity;
routes[29][4] = Infinity;
routes[29][5] = Infinity;
routes[29][6] = Infinity;
routes[29][7] = 3;
routes[29][8] = Infinity;
routes[29][9] = Infinity;
routes[29][10] = Infinity;
routes[29][11] = Infinity;
routes[29][12] = Infinity;
routes[29][13] = Infinity;
routes[29][14] = Infinity;
routes[29][15] = Infinity;
routes[29][16] = 5;
routes[29][17] = Infinity;
routes[29][18] = Infinity;
routes[29][19] = Infinity;
routes[29][20] = Infinity;
routes[29][21] = Infinity;
routes[29][22] = Infinity;
routes[29][23] = Infinity;
routes[29][24] = Infinity;
routes[29][25] = Infinity;
routes[29][26] = Infinity;
routes[29][27] = Infinity;
routes[29][28] = Infinity;
routes[29][29] = 0;
routes[29][30] = Infinity;
routes[29][31] = Infinity;
routes[29][32] = 2;
routes[29][33] = Infinity;
routes[29][34] = Infinity;
routes[29][35] = 6;
routes[30][0] = Infinity;
routes[30][1] = Infinity;
routes[30][2] = 4;
routes[30][3] = Infinity;
routes[30][4] = Infinity;
routes[30][5] = Infinity;
routes[30][6] = Infinity;
routes[30][7] = Infinity;
routes[30][8] = Infinity;
routes[30][9] = 6;
routes[30][10] = Infinity;
routes[30][11] = Infinity;
routes[30][12] = Infinity;
routes[30][13] = Infinity;
routes[30][14] = Infinity;
routes[30][15] = Infinity;
routes[30][16] = Infinity;
routes[30][17] = Infinity;
routes[30][18] = Infinity;
routes[30][19] = Infinity;
routes[30][20] = Infinity;
routes[30][21] = Infinity;
routes[30][22] = Infinity;
routes[30][23] = Infinity;
routes[30][24] = 1;
routes[30][25] = Infinity;
routes[30][26] = Infinity;
routes[30][27] = Infinity;
routes[30][28] = Infinity;
routes[30][29] = Infinity;
routes[30][30] = 0;
routes[30][31] = Infinity;
routes[30][32] = Infinity;
routes[30][33] = 1;
routes[30][34] = Infinity;
routes[30][35] = Infinity;
routes[31][0] = Infinity;
routes[31][1] = Infinity;
routes[31][2] = Infinity;
routes[31][3] = Infinity;
routes[31][4] = 2;
routes[31][5] = Infinity;
routes[31][6] = Infinity;
routes[31][7] = Infinity;
routes[31][8] = Infinity;
routes[31][9] = Infinity;
routes[31][10] = Infinity;
routes[31][11] = 2;
routes[31][12] = Infinity;
routes[31][13] = 2;
routes[31][14] = Infinity;
routes[31][15] = Infinity;
routes[31][16] = Infinity;
routes[31][17] = 2;
routes[31][18] = Infinity;
routes[31][19] = Infinity;
routes[31][20] = Infinity;
routes[31][21] = Infinity;
routes[31][22] = Infinity;
routes[31][23] = 5;
routes[31][24] = Infinity;
routes[31][25] = Infinity;
routes[31][26] = Infinity;
routes[31][27] = Infinity;
routes[31][28] = Infinity;
routes[31][29] = Infinity;
routes[31][30] = Infinity;
routes[31][31] = 0;
routes[31][32] = Infinity;
routes[31][33] = Infinity;
routes[31][34] = Infinity;
routes[31][35] = Infinity;
routes[32][0] = Infinity;
routes[32][1] = Infinity;
routes[32][2] = Infinity;
routes[32][3] = Infinity;
routes[32][4] = 4;
routes[32][5] = Infinity;
routes[32][6] = Infinity;
routes[32][7] = 6;
routes[32][8] = Infinity;
routes[32][9] = Infinity;
routes[32][10] = Infinity;
routes[32][11] = Infinity;
routes[32][12] = Infinity;
routes[32][13] = Infinity;
routes[32][14] = Infinity;
routes[32][15] = Infinity;
routes[32][16] = 3;
routes[32][17] = Infinity;
routes[32][18] = Infinity;
routes[32][19] = Infinity;
routes[32][20] = Infinity;
routes[32][21] = Infinity;
routes[32][22] = Infinity;
routes[32][23] = 2;
routes[32][24] = Infinity;
routes[32][25] = Infinity;
routes[32][26] = Infinity;
routes[32][27] = Infinity;
routes[32][28] = Infinity;
routes[32][29] = 2;
routes[32][30] = Infinity;
routes[32][31] = Infinity;
routes[32][32] = 0;
routes[32][33] = Infinity;
routes[32][34] = Infinity;
routes[32][35] = Infinity;
routes[33][0] = Infinity;
routes[33][1] = Infinity;
routes[33][2] = 3;
routes[33][3] = Infinity;
routes[33][4] = Infinity;
routes[33][5] = Infinity;
routes[33][6] = Infinity;
routes[33][7] = Infinity;
routes[33][8] = Infinity;
routes[33][9] = Infinity;
routes[33][10] = Infinity;
routes[33][11] = Infinity;
routes[33][12] = Infinity;
routes[33][13] = Infinity;
routes[33][14] = Infinity;
routes[33][15] = Infinity;
routes[33][16] = Infinity;
routes[33][17] = Infinity;
routes[33][18] = Infinity;
routes[33][19] = Infinity;
routes[33][20] = Infinity;
routes[33][21] = Infinity;
routes[33][22] = Infinity;
routes[33][23] = Infinity;
routes[33][24] = Infinity;
routes[33][25] = Infinity;
routes[33][26] = Infinity;
routes[33][27] = Infinity;
routes[33][28] = Infinity;
routes[33][29] = Infinity;
routes[33][30] = 1;
routes[33][31] = Infinity;
routes[33][32] = Infinity;
routes[33][33] = 0;
routes[33][34] = Infinity;
routes[33][35] = Infinity;
routes[34][0] = Infinity;
routes[34][1] = Infinity;
routes[34][2] = Infinity;
routes[34][3] = Infinity;
routes[34][4] = Infinity;
routes[34][5] = Infinity;
routes[34][6] = Infinity;
routes[34][7] = Infinity;
routes[34][8] = Infinity;
routes[34][9] = Infinity;
routes[34][10] = Infinity;
routes[34][11] = Infinity;
routes[34][12] = Infinity;
routes[34][13] = Infinity;
routes[34][14] = Infinity;
routes[34][15] = Infinity;
routes[34][16] = Infinity;
routes[34][17] = Infinity;
routes[34][18] = Infinity;
routes[34][19] = 2;
routes[34][20] = Infinity;
routes[34][21] = Infinity;
routes[34][22] = Infinity;
routes[34][23] = 2;
routes[34][24] = Infinity;
routes[34][25] = 2;
routes[34][26] = Infinity;
routes[34][27] = Infinity;
routes[34][28] = Infinity;
routes[34][29] = Infinity;
routes[34][30] = Infinity;
routes[34][31] = Infinity;
routes[34][32] = Infinity;
routes[34][33] = Infinity;
routes[34][34] = 0;
routes[34][35] = Infinity;
routes[35][0] = Infinity;
routes[35][1] = Infinity;
routes[35][2] = 6;
routes[35][3] = Infinity;
routes[35][4] = Infinity;
routes[35][5] = Infinity;
routes[35][6] = Infinity;
routes[35][7] = 4;
routes[35][8] = Infinity;
routes[35][9] = 4;
routes[35][10] = Infinity;
routes[35][11] = Infinity;
routes[35][12] = Infinity;
routes[35][13] = Infinity;
routes[35][14] = Infinity;
routes[35][15] = Infinity;
routes[35][16] = Infinity;
routes[35][17] = Infinity;
routes[35][18] = Infinity;
routes[35][19] = Infinity;
routes[35][20] = Infinity;
routes[35][21] = Infinity;
routes[35][22] = Infinity;
routes[35][23] = Infinity;
routes[35][24] = Infinity;
routes[35][25] = Infinity;
routes[35][26] = Infinity;
routes[35][27] = Infinity;
routes[35][28] = Infinity;
routes[35][29] = 6;
routes[35][30] = Infinity;
routes[35][31] = Infinity;
routes[35][32] = Infinity;
routes[35][33] = Infinity;
routes[35][34] = Infinity;
routes[35][35] = 0;



exports.getRoutes = function() { return routes; }




exports.getShortestRoute = function(graph, source, target, cities) { // graph = getRoutes = array(), source = index of originating city
    
    var dist = new Array();
    var previous = new Array();
    var route;
    
    for(v=0;v<graph.length;v++) {
        dist[v] = Infinity;
        previous[v] = undefined;
    }   

    dist[String(Number(source))] = 0 ;  
    
    console.log('source',source);
    
    var q = graph;
    var vertex;
    
    console.log('Setting dist variable.');
    console.log(dist);
    
    while(q.length > 0)
    {
        u = Infinity;
        for(t=0;t<dist.length;t++)
        {
            //console.log(q[String(Number(t))]);
            if(dist[t] < u && q[t] !== undefined) 
            {
                u = t;
            }
        }
        console.log('u',u);
        
        vertex = q[u];
        
        //console.log(dist);
        console.log('vertex',u);
        console.log('Min distance: '+dist[u]);
        console.log(cities[u+1]);
        
        q[u] = undefined;
                
        if(u == target) {
            route = getSequence(previous, target);
            
            console.log(route);
            break;
        }
        
        if(dist[u] === Infinity)
        {
            break;
        }
console.log(previous);
        for (v in vertex)
        {
            if (String(Number(v)) === v && vertex.hasOwnProperty(v)) 
            {
                if(vertex[v] !== Infinity && vertex[v] != 0)// && !inArray(v, previous))
                {
console.log('Looking at: '+cities[Number(v)+1]);
console.log('vertex',v);
console.log('with distance of: '+vertex[v]);


                    var alt = dist[u] + vertex[v]; // vertex[v] = distance between v & u



console.log('dist[u]',dist[u]);
console.log('vertex[v]',vertex[v]);

 console.log('alt', alt);                   
 
 
                    if(alt < dist[v])
                    {
                        dist[Number(v)] = alt;
                        previous[Number(v)] = u;
                        //q[v][u] = 0;
                    }
                    
                }
            }
            
        }
        
        
        
    }    
    
    
    
    function getSequence(previous, target)
    {
        console.log('previous', previous);
        console.log(target);
        
        var sequence = new Array();
        var u = target
        
        while(previous[u] !== undefined)
        {
            sequence.push(u);
            u = previous[u];
        }
        
    }
    
    function inArray(needle, haystack) {
        var key;
        for(key in haystack) {
            if (String(Number(key)) === key && vertex.hasOwnProperty(key)) 
            {
                if(key == needle) {
                    return true;
                }
            }
        }
        return false;
    }
    
    return { distance: dist, route: previous } ;
}




/*



var citiesById = new Array();
citiesById[1] ='Atlanta';
citiesById[2] ='Boston';
citiesById[3] ='Calgary';
citiesById[4] ='Charleston';
citiesById[5] ='Chicago';
citiesById[6] ='Dallas';
citiesById[7] ='Denver';
citiesById[8] ='Duluth';
citiesById[9] ='El Paso';
citiesById[10] ='Helena';
citiesById[11] ='Houston';
citiesById[12] ='Kansas City';
citiesById[13] ='Las Vegas';
citiesById[14] ='Little Rock';
citiesById[15] ='Los Angeles';
citiesById[16] ='Miami';
citiesById[17] ='Montreal';
citiesById[18] ='Nashville';
citiesById[19] ='New Orleans';
citiesById[20] ='New York City';
citiesById[21] ='Oklahoma City';
citiesById[22] ='Omaha';
citiesById[23] ='Phoenix';
citiesById[24] ='Pittsburgh';
citiesById[25] ='Portland';
citiesById[26] ='Raleigh';
citiesById[27] ='Salt Lake City';
citiesById[28] ='San Francisco';
citiesById[29] ='Santa Fe';
citiesById[30] ='Sault Ste Marie';
citiesById[31] ='Seattle';
citiesById[32] ='St Louis';
citiesById[33] ='Toronto';
citiesById[34] ='Vancouver';
citiesById[35] ='Washington, DC';
citiesById[36] ='Winnipeg';




var stations = new Array();
stations.push([0,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,1,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,3,Infinity,6]);
stations.push([2,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,4,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,4,Infinity,1,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,4,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,4,5,Infinity,Infinity,Infinity,3,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,0,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,6,Infinity,Infinity,4]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,0,Infinity,6,Infinity,Infinity,Infinity,5,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,4,Infinity,Infinity,Infinity,4,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,4]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,1,Infinity,Infinity,6,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,1,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,3,3,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,6,Infinity,Infinity,Infinity,2,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([5,Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,Infinity,3,Infinity,Infinity,Infinity]);
stations.push([1,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity]);
stations.push([4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,3,Infinity,6,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,0,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,2,4,Infinity,Infinity,Infinity,Infinity,2,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,4,Infinity,4,2,Infinity,5,Infinity,1,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,4,Infinity,2,Infinity,Infinity,Infinity,0,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,5,2,Infinity,2,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,6,5,Infinity,Infinity,1,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([2,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,3,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,6,Infinity,0,5,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,5,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,2,Infinity,Infinity,6]);
stations.push([Infinity,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,1,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,1,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,2,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,5,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,4,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,0,Infinity,Infinity,Infinity]);
stations.push([Infinity,Infinity,3,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,1,Infinity,Infinity,0,Infinity,Infinity]);
stations.push([Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,2,Infinity,Infinity,Infinity,2,Infinity,2,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,0,Infinity]);
stations.push([Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,4,Infinity,4,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,6,Infinity,Infinity,Infinity,Infinity,Infinity,0]);

var dist = new Array();

var route = new Array();

for(i=0;i<stations.length;i++) {
    dist[i] = new Array();
    route[i] = new Array();
    for(j=0;j<stations.length;j++) {
        dist[i][j] = stations[i][j];
        route[i][j] = new Array();
        route[i][j].push(i);
    }
}

console.log(dist);

for(k=0;k<stations.length;k++) {
    for(i=0;i<stations.length;i++) {
        for(j=0;j<stations.length;j++) {
            if( dist[i][k] + dist[k][j] < dist[i][j] )
            {
                dist[i][j] = dist[i][k] + dist[k][j];
                route[i][j].push(k);
            }
        
        }
        route[i][j].push();
    }
}

for(i=0;i< route[0][1].length;i++)
{
    j = route[0][1][i]+1;
    console.log(citiesById[j]);


}

console.log(citiesById[2]);


*/
